apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment-employee
  labels:
    app: employee-example-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-example-devops
  template:
    metadata:
      labels:
        app: employee-example-devops
    spec:
      containers:
      - name: employee-example-devops
        image: relari/employee-example-devops
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: app-employee-example-devops
spec:
  type: LoadBalancer
  selector:
    app: employee-example-devops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080