application:
  info:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
  api:
    path: '/api/v1/employees'
  backend:
    errors:
      EMPLOYEE_NOT_SAVE:
        description: 'Error al guardar al empleado.'
        category: INTERNAL_ERROR
      EMPLOYEE_NOT_FOUND:
        description: 'Empleado no encontrado.'
        category: NOT_FOUND
      EMPLOYEE_NOT_UPDATE:
        description: 'Error al actualizar al empleado.'
        category: INTERNAL_ERROR

springdoc:
  api-docs:
    path: '${application.api.path}/openapi'

  swagger-ui:
    path: '${application.api.path}/swagger-ui.html'

server:
  error:
    include-message: always
  port: 8081

logging:
  level:
    com.pe.relari: TRACE