# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - employee-example-devops

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Step 3 - Build with Maven
        run: mvn clean package -DskipTests

      - name: Step 4 - Run unit tests
        run: mvn test

      - name: Obtener hash corto del commit
        id: short_commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Step 5 - Docker build image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-employee-devops:${{ steps.short_commit_hash.outputs.hash }} .

      - name: Step 6 - Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Step 7 - Push de la imagen Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-employee-devops:${{ steps.short_commit_hash.outputs.hash }}

#      - name: Step 4 - List the current directory
#        run: dir
#
#      - name: Step 5 - What is in the target folder
#        run: |
#          cd target
#          dir
#
#      - name: Step 6 - Return root project
#        run: |
#          cd ..
#          cd api-employee-devops
#          dir

